机器学习中涉及大量数据计算，一般会用多维矩阵对数据进行表示，需要了解一些基础的线性代数知识

In [9]:
import numpy as np
#矩阵内积,内积需要保证a的列数和b的行数相同
a = [[1,2,3],[4,5,6]]
b = [[1,2],[4,5], [7,8]]
#用基础的for循环实现
c = np.zeros((len(a), len(b[0])), dtype=np.int32)
# ....此处省略异常处理
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            c[i][j] += a[i][k] * b[k][j]
print(c)

# 使用numpy的dot函数实现
c = np.dot(a,b)
print(c)


[[30 36]
 [66 81]]
[[30 36]
 [66 81]]


In [ ]:
import numpy as np

#矩阵外积
# a = [[1,2,3],[4,5,6]]
# b = [[1,2],[4,5], [7,8]]

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
#用基础的for循环实现外积
a_f = np.ravel(a)
b_f = np.ravel(b)
c = np.zeros((len(a_f), len(b_f)), dtype=np.int32)

for i in range(len(a_f)):
    for j in range(len(b_f)):
        c[i][j] += a_f[i] * b_f[j]
print(c)

#使用numpy的outer函数实现
c = np.outer(a,b)
print(c)



[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]
